// <auto-generated />
using System;
using CookingHelper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CookingHelper.Server.Migrations
{
    [DbContext(typeof(UserListDbContext))]
    [Migration("20240625110712_FeedbackDbContext")]
    partial class FeedbackDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CookingHelper.Model.FeedbackGroup", b =>
                {
                    b.Property<int>("FeedbackGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FeedbackGroupId"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("FeedbackGroupId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("FeedbackGroup", (string)null);
                });

            modelBuilder.Entity("CookingHelper.Model.FeedbackPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OtherSuggestionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("QuestionReplyId")
                        .HasColumnType("int");

                    b.Property<int>("SystemSuggestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OtherSuggestionId");

                    b.HasIndex("QuestionReplyId");

                    b.HasIndex("SystemSuggestionId");

                    b.ToTable("FeedbackPost", (string)null);
                });

            modelBuilder.Entity("CookingHelper.Model.OtherSuggestion", b =>
                {
                    b.Property<int>("OtherSuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OtherSuggestionId"));

                    b.Property<int>("FeedbackGroupId")
                        .HasColumnType("int");

                    b.HasKey("OtherSuggestionId");

                    b.HasIndex("FeedbackGroupId")
                        .IsUnique();

                    b.ToTable("OtherSuggestion", (string)null);
                });

            modelBuilder.Entity("CookingHelper.Model.QuestionReply", b =>
                {
                    b.Property<int>("QuestionReplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("QuestionReplyId"));

                    b.Property<int>("FeedbackGroupId")
                        .HasColumnType("int");

                    b.HasKey("QuestionReplyId");

                    b.HasIndex("FeedbackGroupId")
                        .IsUnique();

                    b.ToTable("QuestionReply", (string)null);
                });

            modelBuilder.Entity("CookingHelper.Model.SystemSuggestion", b =>
                {
                    b.Property<int>("SystemSuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SystemSuggestionId"));

                    b.Property<int>("FeedbackGroupId")
                        .HasColumnType("int");

                    b.HasKey("SystemSuggestionId");

                    b.HasIndex("FeedbackGroupId")
                        .IsUnique();

                    b.ToTable("SystemSuggestion", (string)null);
                });

            modelBuilder.Entity("CookingHelper.Model.UserList", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ShoppingListText")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("UserList", (string)null);
                });

            modelBuilder.Entity("CookingHelper.Model.FeedbackGroup", b =>
                {
                    b.HasOne("CookingHelper.Model.UserList", "UserList")
                        .WithOne("FeedbackGroup")
                        .HasForeignKey("CookingHelper.Model.FeedbackGroup", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserList");
                });

            modelBuilder.Entity("CookingHelper.Model.FeedbackPost", b =>
                {
                    b.HasOne("CookingHelper.Model.OtherSuggestion", "OtherSuggestion")
                        .WithMany("PostList")
                        .HasForeignKey("OtherSuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookingHelper.Model.QuestionReply", "QuestionReply")
                        .WithMany("PostList")
                        .HasForeignKey("QuestionReplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookingHelper.Model.SystemSuggestion", "SystemSuggestion")
                        .WithMany("PostList")
                        .HasForeignKey("SystemSuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OtherSuggestion");

                    b.Navigation("QuestionReply");

                    b.Navigation("SystemSuggestion");
                });

            modelBuilder.Entity("CookingHelper.Model.OtherSuggestion", b =>
                {
                    b.HasOne("CookingHelper.Model.FeedbackGroup", "FeedbackGroup")
                        .WithOne("OtherSuggestion")
                        .HasForeignKey("CookingHelper.Model.OtherSuggestion", "FeedbackGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedbackGroup");
                });

            modelBuilder.Entity("CookingHelper.Model.QuestionReply", b =>
                {
                    b.HasOne("CookingHelper.Model.FeedbackGroup", "FeedbackGroup")
                        .WithOne("QuestionReply")
                        .HasForeignKey("CookingHelper.Model.QuestionReply", "FeedbackGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedbackGroup");
                });

            modelBuilder.Entity("CookingHelper.Model.SystemSuggestion", b =>
                {
                    b.HasOne("CookingHelper.Model.FeedbackGroup", "FeedbackGroup")
                        .WithOne("SystemSuggestion")
                        .HasForeignKey("CookingHelper.Model.SystemSuggestion", "FeedbackGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedbackGroup");
                });

            modelBuilder.Entity("CookingHelper.Model.FeedbackGroup", b =>
                {
                    b.Navigation("OtherSuggestion")
                        .IsRequired();

                    b.Navigation("QuestionReply")
                        .IsRequired();

                    b.Navigation("SystemSuggestion")
                        .IsRequired();
                });

            modelBuilder.Entity("CookingHelper.Model.OtherSuggestion", b =>
                {
                    b.Navigation("PostList");
                });

            modelBuilder.Entity("CookingHelper.Model.QuestionReply", b =>
                {
                    b.Navigation("PostList");
                });

            modelBuilder.Entity("CookingHelper.Model.SystemSuggestion", b =>
                {
                    b.Navigation("PostList");
                });

            modelBuilder.Entity("CookingHelper.Model.UserList", b =>
                {
                    b.Navigation("FeedbackGroup")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
