// <auto-generated />
using System;
using CookingHelper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CookingHelper.Server.Migrations
{
    [DbContext(typeof(UserListDbContext))]
    [Migration("20240721095140_storeItemUpdate")]
    partial class storeItemUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CookingHelper.Model.StoreItem", b =>
                {
                    b.Property<int>("StoreItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Amount")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<int>("StoreListId")
                        .HasColumnType("int");

                    b.HasKey("StoreItemId");

                    b.ToTable("StoreItem", (string)null);
                });

            modelBuilder.Entity("CookingHelper.Model.StoreList", b =>
                {
                    b.Property<int>("StoreListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StoreListId"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("StoreListId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StoreList", (string)null);
                });

            modelBuilder.Entity("CookingHelper.Model.UserList", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ShoppingListText")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("UserList", (string)null);
                });

            modelBuilder.Entity("CookingHelper.Model.StoreItem", b =>
                {
                    b.HasOne("CookingHelper.Model.StoreList", "StoreList")
                        .WithMany("StoreItemList")
                        .HasForeignKey("StoreItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreList");
                });

            modelBuilder.Entity("CookingHelper.Model.StoreList", b =>
                {
                    b.HasOne("CookingHelper.Model.UserList", "UserList")
                        .WithOne("StoreList")
                        .HasForeignKey("CookingHelper.Model.StoreList", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserList");
                });

            modelBuilder.Entity("CookingHelper.Model.StoreList", b =>
                {
                    b.Navigation("StoreItemList");
                });

            modelBuilder.Entity("CookingHelper.Model.UserList", b =>
                {
                    b.Navigation("StoreList");
                });
#pragma warning restore 612, 618
        }
    }
}
